# Generated by Django 4.2.7 on 2023-11-28 21:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('departamento', '0004_alter_departamento_name_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='departamento',
            options={'ordering': ['-name'], 'verbose_name': 'Mi Departamento', 'verbose_name_plural': 'Areas de la empresa'},
        ),
        migrations.RenameField(
            model_name='departamento',
            old_name='short_name',
            new_name='shor_name',
        ),
    ]
